FROM node:18.12.1-alpine3.16
WORKDIR /usr/src/app
COPY package.json yarn* /usr/src/app/

COPY prisma  ./prisma/
COPY tsconfig.json ./
COPY wait-for.sh ./
COPY docker-entrypoint-test.sh ./


RUN chmod +x wait-for.sh \
    && chmod +x docker-entrypoint-test.sh \
    && yarn

COPY . .

RUN npx prisma generate

# EXPOSE 8000

# CMD [ "yarn","test" ]
ENTRYPOINT ["docker-entrypoint-test.sh"]